name: agrokomakchi
description: Agrokomakchi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flex_color_scheme: ^5.1.0
  equatable: ^2.0.5
  collection: ^1.16.0

  printing: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/pdf/



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
